### PR TITLE
Update to 2023.2

### PR DESCRIPTION
**Pull request by iconmaster5326**
This is my attempt at updating this project to the latest version mbeddr supports. Do tell me if this looks correct, and if there are any tests I should run!

### CODE REVIEW

**Comment by iconmaster5326** [comment]
Looks like the Gradle build is failing. Not ready to merge yet.

/draft

**Comment by iconmaster5326** [comment]
The build is failing for the following reason now:

```
> Task :generateBuildscript
ERROR: Unhandled exception in [StandaloneCoroutine{Cancelling}@17a90c4a, Dispatchers.Default]
java.lang.IllegalAccessError: class com.intellij.ide.bootstrap.UiKt$initAwtToolkit$1 (in unnamed module @0x1e324806) cannot access class sun.awt.AWTAutoShutdown (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @0x1e324806
        at com.intellij.ide.bootstrap.UiKt$initAwtToolkit$1.invokeSuspend(ui.kt:141)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Exception in thread "DefaultDispatcher-worker-9" java.lang.IllegalAccessError: class com.intellij.ide.bootstrap.UiKt$initAwtToolkit$1 (in unnamed module @0x1e324806) cannot access class sun.awt.AWTAutoShutdown (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @0x1e324806
        at com.intellij.ide.bootstrap.UiKt$initAwtToolkit$1.invokeSuspend(ui.kt:141)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@17a90c4a, Dispatchers.Default]
execute-generators: generation failed
```

Could this be an error in mps-gradle-plugin?

**Comment by sergej-koscejev** [comment]
MPS 2023.2 requires passing some --add-opens flags to start. mps-gradle-plugin needs to be updated to use the launcher from mps-build-backends (https://github.com/mbeddr/mps-build-backends/tree/main/launcher) which would take care of passing the necessary flags depending on MPS version.

**Comment by iconmaster5326** [comment]
Thanks for the info. I'm taking a look at mps-gradle-plugin now!

**Comment by iconmaster5326** [comment]
It should be ready now. Removing draft status.

**Comment by sergej-koscejev** [comment]
@iconmaster5326 thank you for this PR, I incorporated it on main but made a few changes and published under version [2.0.0](https://github.com/specificlanguages/mps-json/releases/tag/2.0.0).

**Pull request closed without merging**
